---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:

    # TODO: Not supported yet
    #- name: Tower | Cleanup Workflows
    #  import_role:
    #    name: tower
    #    tasks_from: workflow_cleanup.yaml
    #  tags:
    #    - workflow_cleanup

    # TODO: Not supported yet
    #- name: Tower | Cleanup OAuth Application
    #  import_role:
    #    name: tower
    #    tasks_from: applications_cleanup.yaml
    #  tags:
    #    - applications_cleanup


    - name: Tower | Cleanup Job Templates
      import_role:
        name: tower
        tasks_from: job_templates_cleanup.yaml
      tags:
        - jobs_cleanup

    - name: Tower | Cleanup Projects
      import_role:
        name: tower
        tasks_from: projects_cleanup.yaml
      tags:
        - projects_cleanup

    - name: Tower | Cleanup Inventories
      import_role:
        name: tower
        tasks_from: add_inventory_cleanup.yaml
      tags:
        - inventory_cleanup

    - name: Tower | Cleanup Credentials
      import_role:
        name: tower
        tasks_from: credentials_cleanup.yaml
      tags:
        - credentials_cleanup

    - name: Tower | Cleanup Teams
      import_role:
        name: tower
        tasks_from: teams_cleanup.yaml
      tags:
        - teams_cleanup

    - name: Tower | Cleanup Users
      import_role:
        name: tower
        tasks_from: users_cleanup.yaml
      tags:
        - users_cleanup
