---
- hosts: splunk
  become: false
  gather_facts: true
  tasks:

    - name: Splunk | Install Splunk RPM
      import_role:
        name: splunk
        tasks_from: install.yaml

#    - name: Splunk | Configure Logging Aggregator
#      import_role: playbooks/splunk.yaml
#      when: ( splunk.enabled | bool )
