---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:

    - name: Tower | Create Credentials
      import_role:
        name: tower
        tasks_from: credentials.yaml
      tags:
        - credentials

    - name: Tower | Create Teams
      import_role:
        name: tower
        tasks_from: teams.yaml
      tags:
        - teams

    - name: Tower | Create Inventories
      import_role:
        name: tower
        tasks_from: add_inventory.yaml
      tags:
        - inventory

    - name: Tower | Create Projects
      import_role:
        name: tower
        tasks_from: projects.yaml
      tags:
        - projects

    - name: Tower | Create jobs
      import_role:
        name: tower
        tasks_from: job_templates.yaml
      tags:
        - jobs

    - name: Tower | Create Users
      import_role:
        name: tower
        tasks_from: users.yaml
      tags:
        - users

    # TODO: Not supported yet
    #- name: Tower | Create OAuth Applications
    #  import_role:
    #    name: tower
    #    tasks_from: applications.yaml
    #  tags:
    #    - applications

    # TODO: Not supported yet
    #- name: Tower | Create Workflows
    #  import_role:
    #    name: tower
    #    tasks_from: workflow.yaml
    #  tags:
    #    - workflow
