---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:

    - name: Create Credentials
      import_tasks: playbooks/credentials.yaml
      vars:
        action: present
      tags:
        - credentials

    - name: Create Teams
      import_tasks: playbooks/teams.yaml
      vars: 
        action: present
      tags:
        - teams

    - name: Create an inventory
      import_tasks: playbooks/add_inventory.yaml
      vars: 
        action: present
      tags:
        - inventory

    - name: Create Projects
      import_tasks: playbooks/projects.yaml
      vars: 
        action: present
      tags:
        - projects

    - name: Create jobs
      import_tasks: playbooks/job_templates.yaml
      vars: 
        action: present
      tags:
        - jobs

    - name: Create Users
      import_tasks: playbooks/users.yaml
      vars: 
        action: present
      tags:
        - users

    # TODO: Not supported yet
    #- name: Create OAuth Application
    #  import_tasks: playbooks/applications.yaml
    #  tags:
    #    - applications

    # TODO: Not supported yet
    #- name: Configure Splunk Logging Aggregator
    #  import_tasks: playbooks/splunk.yaml
    #  when: ( splunk.enabled | bool )
    #  tags:
    #    - splunk

    # TODO: Not supported yet
    #- name: Create Ansible Tower Workflow
    #  import_tasks: playbooks/workflow.yaml
