---

- name: Add Infrastructure tower inventory
  tower_inventory:
    name: "Infrastructure"
    description: "Infrastructure Servers"
    organization: "{{ tower.organization }}"
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add host to Infrastructure inventory
  delegate_to: localhost
  tower_host:
    name: grimlock-wordpress.redhatgov.io
    description: "Local Host Group"
    inventory: "Infrastructure"
    state: present
    enabled: true
    variables:
      ansible_user: ec2-user
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'

- name: Add Wordpress on RHEL inventory
  tower_inventory:
    name: "Wordpress_RHEL"
    description: "Wordpress RHEL Servers"
    organization: "{{ tower.organization }}"
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add host to Wordpress on RHEL inventory
  tower_host:
    name: grimlock-wordpress.redhatgov.io
    description: "Wordpress RHEL Server"
    inventory: "Wordpress_RHEL"
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add Wordpress on OCP inventory
  delegate_to: localhost
  tower_inventory:
    name: "Wordpress_OCP"
    description: "Wordpress on OCP Servers"
    organization: "{{ tower.organization }}"
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'

- name: Add Amazon Inventory
  tower_inventory:
    name: 'AWS_Dynamic'
    description: "Amazon Instances"
    organization: "{{ tower.organization }}"
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
    variables:
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3
  delegate_to: localhost

- name: Add ec2 inventory source
  tower_inventory_source:
    name: AWS
    description: Hosts from AWS
    source: ec2
    credential: amz
    inventory: 'AWS_Dynamic'
    instance_filters: 'tag:Name=grimlock-wordpress'
    source_regions: 'us-east-1'
    source_vars: "{ ansible_user: ec2-user, ansible_python_interpreter: /usr/bin/python3 }"
    update_on_launch: true
    overwrite: true
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add Satellite Inventory
  tower_inventory:
    name: 'Satellite_Dynamic'
    description: "Instances registered with Satellite"
    organization: "{{ tower.organization }}"
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
    variables:
      ansible_user: ec2-user
  delegate_to: localhost

- name: Add Satellite inventory source
  delegate_to: localhost
  tower_inventory_source:
    name: Satellite
    description: Hosts from Satellite
    inventory: 'Satellite_Dynamic'
    credential: satellite_credential
    source: satellite6
    source_vars: "{ ansible_user: ec2-user }"
    update_on_launch: true
    overwrite: true
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
