---

- name: Inventory | Remove Infrastructure tower inventory
  tower_inventory:
    name: "Infrastructure"
    description: "Infrastructure Servers"
    organization: "{{ tower.organization }}"
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Inventory | Remove Wordpress on RHEL inventory
  tower_inventory:
    name: "Wordpress_RHEL"
    description: "Wordpress RHEL Servers"
    organization: "{{ tower.organization }}"
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Inventory | Remove Wordpress on OCP inventory
  tower_inventory:
    name: "Wordpress_OCP"
    description: "Wordpress on OCP Servers"
    organization: "{{ tower.organization }}"
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Inventory | Remove Amazon Inventory
  tower_inventory:
    name: 'AWS_Wordpress_Inventory'
    description: "Amazon Instances"
    organization: "{{ tower.organization }}"
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
