---
- name: Remove Credential Into Tower
  tower_credential:
    name: '{{ machine_credentials_name }}'
    kind: ssh
    organization: '{{ tower.organization }}'
    tower_config_file: "files/tower_cli.cfg"
    state: absent
  delegate_to: localhost

- name: Remove EC2 Credentials
  tower_credential:
    name: amz
    kind: aws
    organization: '{{ tower.organization }}'
    state: absent
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost
