---
- name: Remove Credential Into Tower
  tower_credential:
    name: '{{ machine_credentials_name }}'
    kind: ssh
    organization: '{{ tower.organization }}'
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
    state: absent
  delegate_to: localhost

- name: Remove EC2 Credentials
  tower_credential:
    name: amz
    kind: aws
    organization: '{{ tower.organization }}'
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
