---
- name: Fetch private key
  slurp:
    src: "{{ host_credentials }}"
  register: aws_ssh_key
  delegate_to: localhost

- name: Add SSH Key Credential Into Tower
  tower_credential:
    name: "{{ machine_credentials_name }}"
    ssh_key_data: "{{ aws_ssh_key['content'] | b64decode }}"
    kind: ssh
    organization: '{{ tower.organization }}'
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  run_once: true
  delegate_to: localhost

- name: Add EC2 Credentials
  tower_credential:
    name: amz
    description: 'Credentials for the AWS API'
    kind: aws
    username: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    password: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    security_token: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"
    organization: '{{ tower.organization }}'
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
  when: ( aws_dynamic_inventory | bool )

- name: Satellite Credentials
  tower_credential:
    name: satellite_credential
    description: 'Credentials for the Satellite Server API'
    kind: satellite6
    username: '{{ satellite_username }}'
    password: '{{ satellite_password }}'
    organization: '{{ tower.organization }}'
    host: '{{ satellite_server }}'
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
  when: ( satellite_dynamic_inventory | bool )
