---
- name: Remove Tower Project for compliance scanning and remediation
  tower_project:
    name: "RHEL_STIGS"
    organization: "{{ tower.organization }}"
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Remove Tower Project for Wordpress on RHEL
  tower_project:
    name: "Wordpress_RHEL"
    organization: "{{ tower.organization }}"
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Remove Tower Project for Wordpress on OCP
  tower_project:
    name: "Wordpress_OCP"
    organization: "{{ tower.organization }}"
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
