---
- name: Add Tower Project for compliance scanning and remediation
  ansible.tower.tower_project:
    name: "RHEL_STIGS"
    description: "Compliance Remediation Project"
    organization: "{{ tower.organization }}"
    scm_update_on_launch: true
    scm_update_cache_timeout: 60
    scm_type: git
    scm_url: 'https://github.com/dmc5179/ansible-workshop-compliance-remediation.git'
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add Tower Project for Wordpress on RHEL
  ansible.tower.tower_project:
    name: "Wordpress_RHEL"
    description: "Wordpress on RHEL Project"
    organization: "{{ tower.organization }}"
    scm_update_on_launch: true
    scm_update_cache_timeout: 60
    scm_type: git
    scm_url: 'https://github.com/dmc5179/ansible-wordpress-rhel.git'
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add Tower Project for Wordpress on OCP
  ansible.tower.tower_project:
    name: "Wordpress_OCP"
    description: "Wordpress on OCP Project"
    organization: "{{ tower.organization }}"
    scm_update_on_launch: true
    scm_update_cache_timeout: 60
    scm_type: git
    scm_url: 'https://github.com/dmc5179/ansible-wordpress-ocp.git'
    custom_virtualenv: "/var/lib/awx/venv/ansible"
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
