---
- name: Remove Tower Project for compliance scanning and remediation
  tower_project:
    name: "RHEL_STIGS"
    organization: "Default"
    state: absent
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

- name: Remove Tower Project for Wordpress on RHEL
  tower_project:
    name: "Wordpress_RHEL"
    organization: "Default"
    state: absent
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

- name: Remove Tower Project for Wordpress on OCP
  tower_project:
    name: "Wordpress_OCP"
    organization: "Default"
    state: absent
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost
