---
- name: Create the Scanning tower team
  tower_team:
    name: Scanning
    description: Team for scanning devices for compliance
    organization: '{{ tower.organization }}'
    state: present
    tower_config_file: 'files/tower_cli.cfg'
  delegate_to: localhost

- name: Create Remediation tower team
  tower_team:
    name: Remediation
    description: Team for remediating devices for compliance
    organization: '{{ tower.organization }}'
    state: present
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

- name: Create Wordpress team
  tower_team:
    name: Wordpress
    description: Team for installing Wordpress
    organization: '{{ tower.organization }}'
    state: present
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost
