---
- name: Create the Scanning tower team
  tower_team:
    name: Scanning
    organization: '{{ tower.organization }}'
    state: absent
    tower_config_file: 'files/tower_cli.cfg'
  delegate_to: localhost

- name: Create Remediation tower team
  tower_team:
    name: Remediation
    organization: '{{ tower.organization }}'
    state: absent
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

- name: Create Wordpress team
  tower_team:
    name: Wordpress
    organization: '{{ tower.organization }}'
    state: absent
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost
