---
- name: Create the Scanning tower team
  tower_team:
    name: Scanning
    description: Team for scanning devices for compliance
    organization: '{{ tower.organization }}'
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Create Remediation tower team
  tower_team:
    name: Remediation
    description: Team for remediating devices for compliance
    organization: '{{ tower.organization }}'
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Create Wordpress team
  tower_team:
    name: Wordpress
    description: Team for installing Wordpress
    organization: '{{ tower.organization }}'
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
