---

# Helpdesk user
- name: Remove tower user helpdesk1
  tower_user:
    username: 'helpdesk1'
    email: 'helpdesk1@example.org'
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

# Engineer user
- name: Remove tower user engineer1
  tower_user:
    username: 'engineer1'
    email: 'engineer1@example.org'
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

# Wordpress user
- name: Remove tower user wordpress1
  tower_user:
    username: 'wordpress1'
    email: 'wordpress1@example.org'
    state: absent
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
