---
# Helpdesk user
- name: Add tower user helpdesk1
  ansible.tower.tower_user:
    username: helpdesk1
    password: redhat1
    email: helpdesk1@example.org
    first_name: Help
    last_name: Desk
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add helpdesk1 to the member role of Scanning Team
  ansible.tower.tower_role:
    user: helpdesk1
    target_team: "Scanning"
    role: member
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add helpdesk1 to the Infrastructure Inventory
  ansible.tower.tower_role:
    user: helpdesk1
    state: present
    role: use
    inventory: "Infrastructure"
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add helpdesk1 to default org
  ansible.tower.tower_role:
    user: helpdesk1
    organization: '{{ tower.organization }}'
    state: present
    role: member
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add helpdesk1 to {{ machine_credentials_name }} credentials
  ansible.tower.tower_role:
    user: helpdesk1
    credential: "{{ machine_credentials_name }}"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add helpdesk1 to Scanning job template
  ansible.tower.tower_role:
    user: helpdesk1
    job_template: "Scanning"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add helpdesk1 to AWS Dynamic Scanning job template
  ansible.tower.tower_role:
    user: helpdesk1
    job_template: "Scanning_Dynamic"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
  when: ( aws_dynamic_inventory | bool )

- name: Add helpdesk1 to Satellite Dynamic Scanning job template
  ansible.tower.tower_role:
    user: helpdesk1
    job_template: "Scanning_Dynamic_Satellite"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
  when: ( satellite_dynamic_inventory | bool )

- name: Add helpdesk1 to RHEL_STIGS project
  ansible.tower.tower_role:
    user: helpdesk1
    project: "RHEL_STIGS"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

# Engineer user
- name: Add tower user engineer1
  ansible.tower.tower_user:
    username: engineer1
    password: redhat1
    email: 'engineer1@example.org'
    first_name: Engineer
    last_name: Doe
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to the member role of Remediation Team
  ansible.tower.tower_role:
    user: engineer1
    target_team: "Remediation"
    role: member
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to the member role of Scanning Team
  ansible.tower.tower_role:
    user: engineer1
    target_team: "Scanning"
    role: member
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to the Infrastructure Inventory
  ansible.tower.tower_role:
    user: engineer1
    state: present
    role: use
    inventory: "Infrastructure"
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to default org
  ansible.tower.tower_role:
    user: engineer1
    organization: '{{ tower.organization }}'
    state: present
    role: member
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to {{ machine_credentials_name }} credentials
  ansible.tower.tower_role:
    user: engineer1
    credential: "{{ machine_credentials_name }}"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to Remediation job template
  ansible.tower.tower_role:
    user: engineer1
    job_template: "Remediation"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to Scanning job template
  ansible.tower.tower_role:
    user: engineer1
    job_template: "Scanning"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add engineer1 to Scanning job template
  ansible.tower.tower_role:
    user: engineer1
    job_template: "Scanning_Dynamic"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
  when: ( aws_dynamic_inventory | bool )

- name: Add engineer1 to Scanning job template
  ansible.tower.tower_role:
    user: engineer1
    job_template: "Scanning_Dynamic_Satellite"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
  when: ( satellite_dynamic_inventory | bool )

- name: Add engineer1 to RHEL_STIGS  project
  ansible.tower.tower_role:
    user: engineer1
    project: "RHEL_STIGS"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

# Wordpress user
- name: Add tower user wordpress1
  ansible.tower.tower_user:
    username: wordpress1
    password: redhat1
    email: wordpress1@example.org
    first_name: Word
    last_name: Press
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add wordpress1 to the member role of Wordpress Team
  ansible.tower.tower_role:
    user: wordpress1
    target_team: "Wordpress"
    role: member
    state: present
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add wordpress1 to default org
  ansible.tower.tower_role:
    user: wordpress1
    organization: '{{ tower.organization }}'
    state: present
    role: member
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add all users to {{ machine_credentials_name }} credentials
  delegate_to: localhost
  ansible.tower.tower_role:
    user: '{{ item }}'
    credential: "{{ machine_credentials_name }}"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  with_items:
    - 'helpdesk1'
    - 'engineer1'
    - 'wordpress1'

- name: Add all users to amz credentials
  delegate_to: localhost
  ansible.tower.tower_role:
    user: '{{ item }}'
    credential: "amz"
    state: present
    role: use 
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  when: ( aws_dynamic_inventory | bool )
  with_items:
    - 'helpdesk1'
    - 'engineer1'
    - 'wordpress1'

- name: Add all users to satellite credentials
  delegate_to: localhost
  ansible.tower.tower_role:
    user: '{{ item }}'
    credential: "satellite_credential"
    state: present
    role: use 
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  when: ( satellite_dynamic_inventory | bool )
  with_items:
    - 'helpdesk1'
    - 'engineer1'
    - 'wordpress1'

- name: Add wordpress1 to wordpress RHEL inventory
  ansible.tower.tower_role:
    user: wordpress1
    inventory: "Wordpress_RHEL"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add wordpress1 to wordpress OCP inventory
  ansible.tower.tower_role:
    user: wordpress1
    inventory: "Wordpress_OCP"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add all users to AWS_Dynamic Inventory
  delegate_to: localhost
  ansible.tower.tower_role:
    user: '{{ item }}'
    inventory: "AWS_Dynamic"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  when: ( aws_dynamic_inventory | bool )
  with_items:
    - 'helpdesk1'
    - 'engineer1'
    - 'wordpress1'

- name: Add all user to Satellite_Dynamic Inventory
  delegate_to: localhost
  ansible.tower.tower_role:
    user: '{{ item }}'
    inventory: "Satellite_Dynamic"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  when: ( satellite_dynamic_inventory | bool )
  with_items:
    - 'helpdesk1'
    - 'engineer1'
    - 'wordpress1'

- name: Add wordpress1 to RHEL job template
  ansible.tower.tower_role:
    user: wordpress1
    job_template: "Wordpress_on_RHEL"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add wordpress1 to OCP job template
  ansible.tower.tower_role:
    user: wordpress1
    job_template: "Wordpress_on_OCP"
    state: present
    role: execute
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add wordpress1 to Wordpress_RHEL project
  ansible.tower.tower_role:
    user: wordpress1
    project: "Wordpress_RHEL"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost

- name: Add wordpress1 to Wordpress_OCP project
  ansible.tower.tower_role:
    user: wordpress1
    project: "Wordpress_OCP"
    state: present
    role: use
    tower_host: '{{ tower.host }}'
    tower_username: '{{ tower.username }}'
    tower_password: '{{ tower.password }}'
    tower_verify_ssl: '{{ tower.verify_ssl }}'
  delegate_to: localhost
