---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
  - name: include vars
    include_vars: change_request_vars.yml

  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: "{{ snow.username }}"
      password: "{{ snow.password }}"
      instance: "{{ snow.instance }}"
      data:
        severity: "{{ snow.severity }}"
        priority: "{{ snow.priority }}"
        short_description: "This is a test opened by Ansible"
    register: new_incident

  - debug:
      var: new_incident.record
