---

- name: Add Infrastructure tower inventory
  tower_inventory:
    name: "Infrastructure"
    description: "Infrastructure Servers"
    organization: "Default"
    state: present
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

# TODO: Don't have permissions to do this?
- name: Add host to Infrastructure inventory
  tower_host:
    name: grimlock-wordpress.redhatgov.io
    description: "Local Host Group"
    inventory: "Infrastructure"
    state: present
    enabled: true
    variables:
      ansible_user: ec2-user
    tower_config_file: "files/tower_cli.cfg"

- name: Add Wordpress on RHEL inventory
  tower_inventory:
    name: "Wordpress_RHEL"
    description: "Wordpress RHEL Servers"
    organization: "Default"
    state: present
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

# TODO: Don't have permissions to do this?
- name: Add host to Wordpress on RHEL inventory
  tower_host:
    name: grimlock-wordpress.redhatgov.io
    description: "Wordpress RHEL Server"
    inventory: "Wordpress_RHEL"
    state: present
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

- name: Add Wordpress on OCP inventory
  tower_inventory:
    name: "Wordpress_OCP"
    description: "Wordpress on OCP Servers"
    organization: "Default"
    state: present
    tower_config_file: "files/tower_cli.cfg"

- name: Add Amazon Inventory
  tower_inventory:
    name: 'AWS_Wordpress_Inventory'
    description: "Amazon Instances"
    organization: "Default"
    state: present
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

- name: Add ec2 inventory source
  tower_inventory_source:
    name: AWS
    description: Hosts from AWS
    source: ec2
    credential: amz
    inventory: AWS_Wordpress_Inventory
#    instance_filters: 'Name=tag:Name,Values=grimlock-wordpress'
    instance_filters: 'tag:Name=grimlock-wordpress'
    update_on_launch: true
    overwrite: true
    state: present
    tower_config_file: "files/tower_cli.cfg"
  delegate_to: localhost

# TODO: Add Satellite as a dynamic source
#- name: Add tower inventory source
#  tower_inventory_source:
#    name: Inventory source
#    description: My Inventory source
#    inventory: My inventory
#    credential: Devstack_credential
#    source: openstack
#    update_on_launch: true
#    overwrite: true
#    source_vars: '{ private: false }'
#    state: present
#    validate_certs: false
