---
- name: Add Credential Into Tower
  tower_credential:
    name: grimlock
    kind: ssh
    organization: Default
    tower_config_file: "files/tower_cli.cfg"
    state: absent
  run_once: true
  delegate_to: localhost

- name: Add EC2 Credentials
  delegate_to: localhost
  run_once: true
  tower_credential:
    name: amz
    kind: aws
    organization: Default
    state: absent
    tower_config_file: "files/tower_cli.cfg"
