---
- name: Fetch private key
  slurp:
    src: "{{ host_credentials }}"
  register: aws_ssh_key

- name: Add Credential Into Tower
  tower_credential:
    name: grimlock
    ssh_key_data: "{{ aws_ssh_key['content'] | b64decode }}"
    kind: ssh
    organization: Default
    tower_config_file: "files/tower_cli.cfg"
  run_once: true
  delegate_to: localhost

- name: Add EC2 Credentials
  delegate_to: localhost
  run_once: true
  tower_credential:
    name: amz
    kind: aws
    username: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    password: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    organization: Default
    tower_config_file: "files/tower_cli.cfg"
