---
- name: Create Scanning job template in tower
  tower_job_template:
    name: "Scanning"
    job_type: "check"
    inventory: "Infrastructure"
    project: "RHEL_STIGS"
    playbook: "stig.yaml"
    credential: "grimlock"
    state: "present"
    tower_config_file: "files/tower_cli.cfg"
    survey_enabled: false
    become_enabled: true
    description: "Job to check host compliance"

- name: Create Remediation job template in tower
  tower_job_template:
    name: "Remediation"
    job_type: "run"
    inventory: "Infrastructure"
    project: "RHEL_STIGS"
    playbook: "stig.yaml"
    credential: "grimlock"
    state: "present"
    tower_config_file: "files/tower_cli.cfg"
    survey_enabled: false
    become_enabled: true
    description: "Job to remediate hosts"

- name: Create Wordpress on RHEL job template in tower
  tower_job_template:
    name: "Wordpress_on_RHEL"
    job_type: "run"
    inventory: "Wordpress_RHEL"
    project: "Wordpress_RHEL"
    playbook: "main.yml"
    credential: "grimlock"
    state: "present"
    tower_config_file: "files/tower_cli.cfg"
    survey_enabled: false
    become_enabled: true
    description: "Job to install Wordpress on RHEL"

- name: Create Wordpress on OCP job in tower
  tower_job_template:
    name: "Wordpress_on_OCP"
    job_type: "run"
    inventory: "Infrastructure"
    project: "Wordpress_OCP"
    playbook: "main.yaml"
    state: "present"
    tower_config_file: "files/tower_cli.cfg"
    survey_enabled: false
    become_enabled: true
    description: "Job to install Wordpress on OpenShift"
