---
# Helpdesk user
- name: Add tower user helpdesk1
  tower_user:
    username: helpdesk1
    password: redhat1
    email: helpdesk1@example.org
    first_name: Help
    last_name: Desk
    state: present
    tower_config_file: "files/tower_cli.cfg"

- name: Add helpdesk1 to the member role of Scanning Team
  tower_role:
    user: helpdesk1
    target_team: "Scanning"
    role: member
    state: present
    tower_config_file: "files/tower_cli.cfg"

- name: Add helpdeks1 to the Infrastructure Inventory
  tower_role:
    user: helpdesk1
    state: present
    role: use
    inventory: "Infrastructure"
    tower_config_file: "files/tower_cli.cfg"

- name: Add helpdesk1 to default org
  tower_role:
    user: helpdesk1
    organization: 'Default'
    state: present
    role: member
    tower_config_file: "files/tower_cli.cfg"

- name: Add helpdesk1 to grimlock credentials
  tower_role:
    user: helpdesk1
    credential: "grimlock"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

- name: Add helpdesk1 to Infrastructure inventory
  tower_role:
    user: helpdesk1
    inventory: "Infrastructure"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

- name: Add helpdesk1 to Scanning job template
  tower_role:
    user: helpdesk1
    job_template: "Scanning"
    state: present
    role: execute
    tower_config_file: "files/tower_cli.cfg"

- name: Add helpdesk1 to RHEL_STIGS project
  tower_role:
    user: helpdesk1
    project: "RHEL_STIGS"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

# Engineer user
- name: Add tower user engineer1
  tower_user:
    username: engineer1
    password: redhat1
    email: engineer1@example.org
    first_name: Engineer
    last_name: Doe
    state: present
    tower_config_file: "files/tower_cli.cfg"

- name: Add engineer1 to the member role of Remediation Team
  tower_role:
    user: engineer1
    target_team: "Remediation"
    role: member
    state: present
    tower_config_file: "files/tower_cli.cfg"

- name: Add engineer1 to the Infrastructure Inventory
  tower_role:
    user: engineer1
    state: present
    role: use
    inventory: "Infrastructure"
    tower_config_file: "files/tower_cli.cfg"

- name: Add engineer1 to default org
  tower_role:
    user: engineer1
    organization: 'Default'
    state: present
    role: member
    tower_config_file: "files/tower_cli.cfg"

- name: Add engineer1 to grimlock credentials
  tower_role:
    user: engineer1
    credential: "grimlock"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

- name: Add engineer1 to Infrastructure inventory
  tower_role:
    user: engineer1
    inventory: "Infrastructure"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

- name: Add engineer1 to Remediation job template
  tower_role:
    user: engineer1
    job_template: "Remediation"
    state: present
    role: execute
    tower_config_file: "files/tower_cli.cfg"

- name: Add engineer1 to RHEL_STIGS  project
  tower_role:
    user: engineer1
    project: "RHEL_STIGS"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

# Wordpress user
- name: Add tower user wordpress1
  tower_user:
    username: wordpress1
    password: redhat1
    email: wordpress1@example.org
    first_name: Word
    last_name: Press
    state: present
    tower_config_file: "files/tower_cli.cfg"

- name: Add wordpress1 to the member role of Wordpress Team
  tower_role:
    user: wordpress1
    target_team: "Wordpress"
    role: member
    state: present
    tower_config_file: "files/tower_cli.cfg"

- name: Add wordpress1 to the Infrastructure Inventory
  tower_role:
    user: wordpress1
    state: present
    role: use
    inventory: "Wordpress_RHEL"
    tower_config_file: "files/tower_cli.cfg"

- name: Add wordpress1 to default org
  tower_role:
    user: wordpress1
    organization: 'Default'
    state: present
    role: member
    tower_config_file: "files/tower_cli.cfg"

- name: Add wordpress1 to grimlock credentials
  tower_role:
    user: wordpress1
    credential: "grimlock"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

- name: Add wordpress1 to wordpress inventory
  tower_role:
    user: wordpress1
    inventory: "Wordpress_RHEL"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"

- name: Add wordpress1 to RHEL job template
  tower_role:
    user: wordpress1
    job_template: "Wordpress_on_RHEL"
    state: present
    role: execute
    tower_config_file: "files/tower_cli.cfg"

- name: Add wordpress1 to Wordpress_RHEL project
  tower_role:
    user: wordpress1
    project: "Wordpress_RHEL"
    state: present
    role: use
    tower_config_file: "files/tower_cli.cfg"
